name: Social Readme

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  update-social:
    runs-on: ubuntu-latest
    steps:
      - uses: luyao777/social-readme@main
        with:
          blog_rss_link: https://feed.cnblogs.com/blog/u/249615/rss/
